/* Hallmark · existing palette, quiet session controls · pre-emit critique: P5 H5 E4 S5 R5 V4 */
import { useEffect, useState } from 'react';
import { Copy, Plus, Users, ArrowLeft } from 'lucide-react';
import { OperationGame } from '../workbench/OperationGame';
import { GameNavigation, TeamRoom } from './TeamRoom';
import { creationProtection, localRead, localWrite, roomApi, roomLink, RoomInfo, TeamInfo, TeamResponse } from './roomApi';
import { RoomResults } from './RoomResults';
import { FinishDialog } from './FinishDialog';
import { ReviewForm } from './ReviewForm';
import './rooms.css';
const missionNames=['El eslabón acaparador','Responde fuera de rango','Protege el ERP'];
function CopyLink({value,label}:{value:string;label:string}) {
  const [message,setMessage]=useState('');
  return <label className="op-label room-link">{label}<div><input className="op-input" value={value} readOnly onFocus={e=>e.target.select()}/><button className="op-icon-button" aria-label={`Copiar ${label}`} onClick={async()=>{try{await navigator.clipboard.writeText(value);setMessage('Enlace copiado');}catch{setMessage('Selecciona el enlace para copiarlo.');}}}><Copy size={16} aria-hidden="true"/></button></div><span className="op-small" role="status">{message}</span></label>;
}
function TeacherRoom({id,token}:{id:string;token:string}) {
  const [room,setRoom]=useState<RoomInfo|null>(null);
  const [teams,setTeams]=useState<TeamInfo[]>([]);
  const [error,setError]=useState('');const [connected,setConnected]=useState(false);const [busy,setBusy]=useState(false);
  const [qr,setQr]=useState('');
  const [sharing,setSharing]=useState(false);
  const [finishing,setFinishing]=useState(false);
  const [refresh,setRefresh]=useState(0);
  const link=roomLink(id);
  useEffect(()=>{let active=true;import('qrcode').then(q=>q.toDataURL(link,{width:240,margin:2,errorCorrectionLevel:'M'})).then(value=>{if(active)setQr(value);}).catch(()=>{if(active)setError('No se pudo generar el QR. Puedes compartir el enlace público.');});return()=>{active=false;};},[link]);
  useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const data=await roomApi<{room:RoomInfo;teams:TeamInfo[]}>(`/${id}/control`,token);if(active){setRoom(previous=>!previous||data.room.version>=previous.version?data.room:previous);setTeams(data.teams);setConnected(true);}}catch(e){if(active){setConnected(false);setError((e as Error).message);}}finally{if(active)timer=setTimeout(poll,2000);}};void poll();return()=>{active=false;clearTimeout(timer);};},[id,token,refresh]);
  const control=async(round:number,open:boolean)=>{if(!room)return;setBusy(true);setError('');try{const data=await roomApi<{room:RoomInfo}>(`/${id}/control`,token,'PATCH',{round,open,version:room.version});setRoom(data.room);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const finish=async()=>{if(!room)return;setBusy(true);setError('');try{const data=await roomApi<{room:RoomInfo}>(`/${id}/finish`,token,'POST',{version:room.version,confirm:true});setRoom(data.room);setFinishing(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <section className="room-control" aria-label="Control docente"><header className="room-control-head"><div><span className="op-small">Control docente · enlace privado</span><h2>{room?.title ?? 'Conectando con la sala…'}</h2></div><span role="status">{connected?'Conectado':'Sin conexión'}</span></header>
    <details className="room-sharing" open={sharing} onToggle={e=>setSharing(e.currentTarget.open)}><summary>Invitar equipos y guardar enlace docente</summary><div className="room-sharing-body">{qr && <img src={qr} width={240} height={240} alt="QR del enlace público para entrar a la sala"/>}<div><CopyLink value={link} label="Enlace para equipos"/><CopyLink value={roomLink(id,token)} label="Enlace privado docente"/><p className="op-small">Comparte el QR o el enlace para equipos. Conserva el enlace docente para recuperar el control.</p>{['localhost','127.0.0.1'].includes(window.location.hostname)&&<p className="op-small">Para teléfonos, abre esta página usando la IP de tu computador en la misma red antes de compartir el QR.</p>}</div></div></details>
    <div className="room-round-controls" aria-label="Abrir misiones">{missionNames.map((name,index)=><button key={name} className={`op-button ${room?.round===index && room.open?'op-button-primary':''}`} disabled={!connected||busy||!!room?.completedAt} onClick={()=>control(index,true)}>Abrir misión {index+1}</button>)}<button className="op-button" disabled={!connected||busy||!room?.open||!!room?.completedAt} onClick={()=>control(room!.round!,false)}>Cerrar misión</button></div>
    <p className="room-round-status" role="status">{room?.completedAt?'Actividad finalizada':room?.round===null?'Esperando apertura':room?`Misión ${room.round!+1}: ${missionNames[room.round!]} · ${room.open?'Abierta':'Cerrada'}`:'Conectando…'}</p>
    {!room?.completedAt&&<div className="room-finish-action"><div><strong>Cierre general</strong><p>Publica el ganador con los puntos recibidos, aunque queden misiones pendientes.</p></div><button className="op-button op-button-primary" disabled={!connected||busy||!room} onClick={()=>{setError('');setFinishing(true);}}>Finalizar actividad</button></div>}
    <FinishDialog open={finishing} busy={busy} teams={teams.length} incomplete={teams.filter(team=>(team.score?.completed??0)<3).length} pendingReviews={teams.reduce((n,team)=>n+(team.score?.pendingReviews??0),0)} error={error} onCancel={()=>setFinishing(false)} onConfirm={()=>void finish()}/>
    {error&&!finishing&&<p className="room-feedback" role="alert">{error}</p>}
    {room?.results&&<RoomResults results={room.results}/>}
    <div className="op-section-head"><h3>Avance de equipos</h3><span className="op-small">{teams.length} equipos · actualización cada 2 segundos</span></div>
    {teams.length===0?<p className="room-waiting">Comparte el enlace público para que los equipos entren con su nombre.</p>:<div className="room-team-list">{teams.map(team=><article key={team.id} className="room-team"><div className="room-team-score"><h4>{team.name}</h4><strong>{team.score?.total??0}/75 puntos</strong></div><div className="room-team-missions">{missionNames.map((name,index)=>{const prefix=`round-${index}:`;const criteria=team.state[prefix+'criteria'] as {passed:boolean;detail:string}[]|undefined;const submission=team.state[prefix+'submission'] as {explanation:string;order:string;impact:string}|null;const started=!!team.state[prefix+'handlers']||!!team.state[prefix+'http'];return <details key={index}><summary><span>Misión {index+1}</span><strong>{criteria?.filter(c=>c.passed).length??0}/3</strong><span>{submission?'Entrega recibida':started?'En progreso':'Sin empezar'}</span></summary><div><p className="op-small">{name} · {team.score?.rounds[index].total??0}/25 puntos</p>{criteria?.map((criterion,i)=><p key={i}>{criterion.passed?'✓':'○'} {criterion.detail}</p>)}{submission&&<dl><dt>Quién respondió</dt><dd>{submission.explanation}</dd><dt>Justificación del orden</dt><dd>{submission.order}</dd><dt>Consecuencia arquitectónica</dt><dd>{submission.impact}</dd></dl>}{submission&&<ReviewForm key={`${team.id}:${index}:${JSON.stringify(submission)}:${JSON.stringify(team.reviews?.[index]??null)}`} team={team} round={index} roomId={id} token={token} disabled={!connected||!!room?.completedAt} onSaved={()=>setRefresh(value=>value+1)}/>}</div></details>;})}</div></article>)}</div>}
  </section>;
}
function JoinRoom({id,...navigation}:GameNavigation&{id:string}) {
  const [credential,setCredential]=useState(()=>{const value=localRead<{token:string}>(`cor-room:${id}:credential`);return value && typeof value.token==='string' && /^[A-Za-z0-9_-]{43}$/.test(value.token)?value:null;});
  const [session,setSession]=useState<TeamResponse|null>(null);const [room,setRoom]=useState<RoomInfo|null>(null);
  const [name,setName]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [stored,setStored]=useState(true);
  useEffect(()=>{let active=true;setSession(null);setError('');const load=async()=>{try{if(credential?.token){const response=await roomApi<TeamResponse>(`/${id}/work`,credential.token);if(active)setSession(response);}else{const response=await roomApi<{room:RoomInfo}>(`/${id}`);if(active)setRoom(response.room);}}catch(e){if(active)setError((e as Error).message);}};void load();return()=>{active=false;};},[id,credential]);
  const join=async()=>{setBusy(true);setError('');try{const response=await roomApi<TeamResponse>(`/${id}/join`,undefined,'POST',{name});setStored(localWrite(`cor-room:${id}:credential`,{token:response.token}));setCredential({token:response.token!});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  if(room?.results)return <RoomResults results={room.results}/>;
  if(session&&credential)return <>{!stored&&<p className="room-feedback" role="status">El navegador no permite recordar tu clave. Mantén esta pestaña abierta.</p>}<TeamRoom key={session.team.id} session={session} token={credential.token} {...navigation}/></>;
  return <section className="room-lobby"><h2>{room?.title??'Entrar a la sala'}</h2>{credential?<p>Recuperando equipo…</p>:<><p>Un nombre por equipo. Usen un dispositivo para operar la cadena.</p><form onSubmit={e=>{e.preventDefault();void join();}}><label className="op-label" htmlFor="room-team-name">Nombre del equipo<input id="room-team-name" className="op-input" value={name} onChange={e=>setName(e.target.value)} maxLength={60} required autoComplete="off"/></label><button className="op-button op-button-primary" disabled={busy||!room} type="submit">Entrar con mi equipo</button></form></>}{error&&<p className="room-feedback" role="alert">{error}</p>}{credential&&error&&<button className="op-button" onClick={()=>window.location.reload()}>Reintentar conexión</button>}</section>;
}
export function RoomHub(navigation:GameNavigation) {
  const [route,setRoute]=useState(window.location.hash);
  const [title,setTitle]=useState('Operación: Cadena Rota');const [code,setCode]=useState('');
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [creationKey,setCreationKey]=useState('');
  const [protectedCreation,setProtectedCreation]=useState(false);
  const [capabilitiesReady,setCapabilitiesReady]=useState(false);
  const [lastControl,setLastControl]=useState(()=>localRead<string>('cor-room:last-control'));
  useEffect(()=>{const change=()=>setRoute(window.location.hash);window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  useEffect(()=>{if(route!=='#salas')return;let active=true;setCapabilitiesReady(false);creationProtection().then(protectedKey=>{if(active){setProtectedCreation(protectedKey);setCapabilitiesReady(true);}}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false;};},[route]);
  const create=async()=>{setBusy(true);setError('');try{const data=await roomApi<{room:RoomInfo;token:string}>('',undefined,'POST',{title},protectedCreation?{'X-Room-Creation-Key':creationKey}:undefined);setCreationKey('');const link=roomLink(data.room.id,data.token);localWrite('cor-room:last-control',link);setLastControl(link);window.location.hash=`sala/${data.room.id}/docente/${data.token}`;}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const match=/^#sala\/([a-f0-9]{12})(?:\/docente\/([A-Za-z0-9_-]{43}))?$/.exec(route);
  const lobby=route==='#salas';
  return <div className="operation-game room-hub">
    {!match&&!lobby?<><div className="room-entry"><span>¿Actividad en clase?</span><button className="op-button" onClick={()=>{window.location.hash='salas';}}><Users size={16} aria-hidden="true"/>Salas de equipos</button></div><OperationGame {...navigation}/></>:<><button className="op-button op-button-quiet room-back" onClick={()=>{window.location.hash=lobby?'laboratorio/desafios':'salas';}}><ArrowLeft size={16} aria-hidden="true"/>{lobby?'Práctica individual':'Volver a salas'}</button>{match?(match[2]?<TeacherRoom key={route} id={match[1]} token={match[2]}/>:<JoinRoom key={route} id={match[1]} {...navigation}/>):<section className="room-lobby"><h2>Salas de desafíos</h2><p>El docente abre las misiones. Los equipos reparan su propia cadena y entregan una explicación.</p><form onSubmit={e=>{e.preventDefault();void create();}}><label className="op-label" htmlFor="room-title">Nombre de la sala<input id="room-title" className="op-input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required/></label>{protectedCreation&&<label className="op-label" htmlFor="room-creation-key">Clave docente para crear salas<input id="room-creation-key" className="op-input" type="password" value={creationKey} onChange={e=>setCreationKey(e.target.value)} maxLength={128} required autoComplete="off"/></label>}<button className="op-button op-button-primary" type="submit" disabled={busy||!capabilitiesReady}><Plus size={16} aria-hidden="true"/>Crear sala docente</button></form>{lastControl&&<a className="op-button" href={lastControl}>Recuperar último control docente</a>}<form onSubmit={e=>{e.preventDefault();const id=code.trim().match(/(?:sala\/)?([a-f0-9]{12})(?:$|\/)/)?.[1];if(id)window.location.hash=`sala/${id}`;else setError('Escribe el código de 12 caracteres o pega el enlace de la sala.');}}><label className="op-label" htmlFor="room-code">Código o enlace de sala<input id="room-code" className="op-input" value={code} onChange={e=>setCode(e.target.value)} required/></label><button className="op-button" type="submit">Entrar a una sala</button></form>{error&&<p className="room-feedback" role="alert">{error}</p>}</section>}</>}
  </div>;
}
